#+TITLE: C++ Primer Exercise Notes
#+AUTHOR: Donald Willcox

The C++ Primer, 5th Edition, by Lippman, Lajoie, and Moo is here
denoted ``CPPP5''.

* Tips

** Bash - Show Return Value

To see return values from the last run program or command, use `$?`:

#+BEGIN_EXAMPLE
$ ./exercise-1.1-dw.exe
$ echo $?
0
#+END_EXAMPLE


* Chapter 1

** Exercise 1.1

main() returns 0

I get the return value 0

Just as expected.

** Exercise 1.2

main() returns -1

I get the return value 255

Lupe suggested this is because of how signed numbers are represented
on 8 bits, cf pg 34 of CPPP5. The program is returning -1 as a signed
integer, in accordance with the declared return value of `main()` but
bash seems to be displaying it as an unsigned integer instead.

This is confirmed by the GNU specifications for [[https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html#Exit-Status][Exit Status codes]] and
[[https://www.gnu.org/software/libc/manual/html_node/Process-Completion-Status.html][Process Completion Status Macros]] which dictate that if the process has
exited, then the exit status macro ``returns the low-order 8 bits of
the exit status value from the child process'' which is interpreted as
an unsigned integer (0-255).

Furthermore, the mapping between the signed integer returned by the
C++ program and the unsigned 8-bit exit status is determined by the
two's complement binary representation of negative numbers used by
most modern computers. In this representation, `x*` is the binary
representation of the negative number with magnitude `x` and is
defined by `x* = 2^N - x` on N bits. Equivalently, the binary
representation of the negative number can be obtained from the binary
representation of its magnitude by flipping its bits and adding one.

So, a C++ integer exit status of -1 is represented on 16 bits by
0xFFFF in two's complement, and the lowest 8 bits are 0xFF, which
interpreted as an unsigned integer yields 2^8 - 1 = 255.

** Exercise 1.3
   
The Hello, World program. It works.

** Exercise 1.4

Print the product of two integers from command line.

It works.

** Exercise 1.5

Use separate statement per operand.

It works.

** Exercise 1.6

The program fragment is not legal because the first `cout` line
terminates in `;` and there are no instances of `cout` on the
following lines, thus the `<<` operators on those lines lack an
`ostream`. Alternately, just get rid of the terminating `;` on the
first two lines of the `cout`.

Fixed.

** Exercise 1.7

Attempting improperly nested comments ...

Got following compiler error.

```
g++ -Wall -pedantic -std=c++11 -o exercise-1.7-dw.ex exercise-1.7-dw.cpp
exercise-1.7-dw.cpp: In function ‘int main()’:
exercise-1.7-dw.cpp:3:34: error: ‘nest’ was not declared in this scope
   /* Begin comment and try to */ nest the comments /* like so. */
                                  ^
GNUmakefile:10: recipe for target 'exercise-1.7-dw.ex' failed
make: *** [exercise-1.7-dw.ex] Error 1
```

** Exercise 1.8

Line 3 does not compile because the first quote is within a comment,
leaving the second quote without a terminating quote character.

All other lines compile because the compiler searches from the opening
`/*` to the next consecutive closing `*/`.

